package Games;
import java.util.Scanner;

/*This is the game to predict the numbers between 0-9
If the system generated and user predicted numbers are same then you won the match
If the user not predicted the same numbers as generated by the system then you have try one more or many attempts
This program runs in infinite loop until and unless if you enter the values less than 0 and invalid number
If the Number is greater than 9 then it exits from the program
In this program You can modify the range of the random numbers */

public class NumberGuess {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		System.out.println("Welcome to Number Guess Game");
//		To call the GuessNumber
		GuessNumber();

	}
	public static void GuessNumber()
	{
		Scanner s = new Scanner(System.in);
		int number = 0; 
		while(number > -1)
		{
			int Random_Number = (int)(Math.random() * 10);
			System.out.println("Enter the Number between 0 - 9");
			int num = s.nextInt();
			if(num > 9) {
//				Here we can change this to tell the user to Enter the valid number message
				System.exit(0);
			}
			if(Random_Number == num)
			{
				System.out.println("Yes! you won");
			}else {
				System.out.println("Better Luck next time");
				System.out.println("The Random Number is " + Random_Number);
			}
			System.out.println();
		}
	}
}
